services:
  mongo:
    image: mongo
    container_name: mongo-redsocial
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net
          
  cliente-mongo:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - backend-net
          
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - redis-net
    volumes:
      - redis_insight:/db
  api:
    image: api-redsocial:1.0.1
    ports: 
      - 5000:3000
    environment:
      PORT: 3000
      MONGO_URL: mongodb://admin:admin123@mongo:27017/redsocial?authSource=admin
      REDIS_URL: redis://:17Sev!JS@redis:6379 
    depends_on:
      - mongo  
      - redis
    networks:
      - backend-net
      - redis-net

volumes:
  mongo-data:
  redis-data:
  redis_insight:

networks:
  backend-net:
  redis-net:
